// The build-time palette (generated by tools/palette, never hand-edited) and palette validation.

import { hexToRgb } from '../color.ts';
import type { Palette, PaletteColor, Rgb } from '../types.ts';
import raw98138 from './98138.json' with { type: 'json' };

export class PaletteError extends Error {
  override name = 'PaletteError';
}

type Obj = Record<string, unknown>;

const isObj = (v: unknown): v is Obj => typeof v === 'object' && v !== null && !Array.isArray(v);

function str(o: Obj, key: string, path: string): string {
  const v = o[key];
  if (typeof v !== 'string') throw new PaletteError(`${path}.${key}: expected a string`);
  return v;
}

function nullableStr(o: Obj, key: string, path: string): string | null {
  const v = o[key];
  if (v === null) return null;
  if (typeof v !== 'string') throw new PaletteError(`${path}.${key}: expected a string or null`);
  return v;
}

function num(o: Obj, key: string, path: string, { int = false, min = -Infinity } = {}): number {
  const v = o[key];
  if (typeof v !== 'number' || !Number.isFinite(v) || (int && !Number.isInteger(v)) || v < min) {
    throw new PaletteError(`${path}.${key}: expected ${int ? 'an integer' : 'a number'} >= ${min}`);
  }
  return v;
}

function nullableNum(o: Obj, key: string, path: string, opts: { int?: boolean; min?: number } = {}): number | null {
  return o[key] === null ? null : num(o, key, path, opts);
}

function bool(o: Obj, key: string, path: string): boolean {
  const v = o[key];
  if (typeof v !== 'boolean') throw new PaletteError(`${path}.${key}: expected a boolean`);
  return v;
}

const TIERS: readonly PaletteColor['tier'][] = ['core', 'extended', 'rare'];

function color(v: unknown, path: string): PaletteColor {
  if (!isObj(v)) throw new PaletteError(`${path}: expected an object`);
  const hex = str(v, 'hex', path);
  let rgb: Rgb;
  try {
    rgb = hexToRgb(hex);
  } catch {
    throw new PaletteError(`${path}.hex: expected #RRGGBB, got ${JSON.stringify(hex)}`);
  }
  const given = v.rgb;
  if (!Array.isArray(given) || given.length !== 3 || given.some((c, i) => c !== rgb[i])) {
    throw new PaletteError(`${path}.rgb: must equal the hex value ${hex}`);
  }
  const tier = str(v, 'tier', path);
  if (!(TIERS as readonly string[]).includes(tier)) throw new PaletteError(`${path}.tier: expected one of ${TIERS.join(', ')}`);
  const code = str(v, 'code', path);
  if (!/^\S{2}$/u.test(code)) throw new PaletteError(`${path}.code: expected 2 non-space characters`);
  const elementId = nullableStr(v, 'elementId', path);
  if (elementId !== null && !/^\d+$/.test(elementId)) throw new PaletteError(`${path}.elementId: expected digits`);
  return {
    id: num(v, 'id', path, { int: true, min: 0 }),
    name: str(v, 'name', path),
    hex: hex.toUpperCase(),
    rgb,
    code,
    tier: tier as PaletteColor['tier'],
    defaultEnabled: bool(v, 'defaultEnabled', path),
    blId: nullableNum(v, 'blId', path, { int: true, min: 0 }),
    blName: nullableStr(v, 'blName', path),
    legoId: nullableNum(v, 'legoId', path, { int: true, min: 0 }),
    elementId,
    pab: bool(v, 'pab', path),
    pabDkk: nullableNum(v, 'pabDkk', path, { min: 0 }),
    pabEur: nullableNum(v, 'pabEur', path, { min: 0 }),
    blEur: nullableNum(v, 'blEur', path, { min: 0 }),
  };
}

/**
 * Validates palette JSON and returns a normalised copy. Throws PaletteError naming the first problem:
 * missing or mistyped fields, rgb that does not match hex, duplicate ids or codes, more than 255
 * colours, colour ids above 65535 (the share codec stores u16).
 */
export function loadPalette(json: unknown): Palette {
  if (!isObj(json)) throw new PaletteError('palette: expected an object');
  const list = json.colors;
  if (!Array.isArray(list) || list.length === 0) throw new PaletteError('palette.colors: expected a non-empty array');
  if (list.length > 255) throw new PaletteError('palette.colors: at most 255 colours');
  const colors = list.map((c, i) => color(c, `palette.colors[${i}]`));
  const ids = new Set<number>(), codes = new Set<string>();
  for (const c of colors) {
    if (c.id > 0xffff) throw new PaletteError(`palette: colour id ${c.id} does not fit in 16 bits`);
    if (ids.has(c.id)) throw new PaletteError(`palette: duplicate colour id ${c.id}`);
    if (codes.has(c.code)) throw new PaletteError(`palette: duplicate code ${c.code}`);
    ids.add(c.id);
    codes.add(c.code);
  }
  const part = str(json, 'part', 'palette');
  if (!/^[\x21-\x7e]{1,255}$/.test(part)) throw new PaletteError('palette.part: expected printable ASCII');
  return {
    part,
    partName: str(json, 'partName', 'palette'),
    blPart: str(json, 'blPart', 'palette'),
    rev: str(json, 'rev', 'palette'),
    pricesAsOf: str(json, 'pricesAsOf', 'palette'),
    blEurDefault: num(json, 'blEurDefault', 'palette', { min: 0 }),
    attribution: str(json, 'attribution', 'palette'),
    colors,
  };
}

/** Round 1x1 tile (98138), 40 colours; generated by tools/palette. */
export const DEFAULT_PALETTE: Palette = loadPalette(raw98138);
